'use strict';

/** @type {import('sequelize-cli').Migration} */

let options = {};
if (process.env.NODE_ENV === 'production') {
  options.schema = process.env.SCHEMA;  // define your schema in options object
}

module.exports = {
  up: async (queryInterface, Sequelize) => {
    options.tableName = 'Spots';
    return queryInterface.bulkInsert(options, [
      {
        ownerId: 1,
        address: "123 Disney Lane",
        city: "Anaheim",
        state: "California",
        country: "United States of America",
        lat: 37.7645358,
        lng: -122.4730327,
        name: "Disneyland",
        description: "California's Disneyland Park dubs itself 'The Happiest Place on Earth,' and indeed it's known for bringing smiles to the faces of those who visit. This park houses the Sleeping Beauty Castle, the famous Pirates of the Caribbean boat ride and multiple themed 'lands' meant to create unique experiences that families will never forget. The most recent addition to Disneyland – Star Wars: Galaxy's Edge – features lightsaber-building workshops, Star Wars-themed food, a large collection of rides and more.",
        price: 123,
      },
      {
        ownerId: 2,
        address: "6561 Beach Boulevard",
        city: "Buena Park",
        state: "California",
        country: "United States of America",
        lat: 33.8652,
        lng: -117.9985,
        name: "Knott's Berry Farm",
        description: "Knott's Berry Farm near Anaheim may have started as a small berry farm in the early 1920s, but today's visitors will find a large theme park featuring four distinct regions, all with unique rides and attractions. The Old West Ghost Town is equipped with Western-themed coasters and a saloon, while Camp Snoopy's rides and attractions are designed for young kids. Fiesta Village, meanwhile, recognizes California's Hispanic roots in its architecture and rides. The fourth area, Knott's Boardwalk, takes inspiration from Southern California's beach vibes while offering the park's most extreme roller coasters and a stage for live entertainment.",
        price: 60,
      },
      {
        ownerId: 2,
        address: "26101 Magic Mountain Pkwy",
        city: "Valencia",
        state: "California",
        country: "United States of America",
        lat: 34.3917,
        lng: -118.5426,
        name: "Six Flags",
        description: "Six Flags Magic Mountain is perfect for families with kids of all ages and for adults who want to enjoy some thrills. Family rides at this top California theme park include everything you would expect, from bumper cars to a swing ride to a miniature train for all ages. Meanwhile, the park's thrill rides will spin you every which way or drop you up to 250-plus feet.",
        price: 80,
      },
      {
        ownerId: 2,
        address: "100 Universal City Plaza",
        city: "Los Angeles",
        state: "California",
        country: "United States of America",
        lat: 34.136518,
        lng: -118.356051,
        name: "Universal Studios Hollywood",
        description: 'Universal Studios Hollywood is a great place to enjoy themed rides and see characters and sets from stories you love. Attractions are based on popular franchises, including "Harry Potter," "King Kong," "The Simpsons" and more; the new Super Nintendo World even boasts a Mario Kart ride experience. While many of these attractions include rides, Universal Studios Hollywood also offers memorable entertainment running the gamut from encounters with "Jurassic World" dinosaurs to "Despicable Me" carnival games.',
        price: 100,
      },
      {
        ownerId: 1,
        address: "2700 Dollywood Parks Blvd",
        city: "Pigeon Forge",
        state: "Tenessee",
        country: "United States of America",
        lat: 35.474600,
        lng: -83.32372,
        name: "Dollywood",
        description: "Dollywood is home to 160 acres of theme park and water park fun with more than 50 world-class rides and a family-friendly atmosphere. Top attractions at the Dolly Parton brainchild include the Tennessee Tornado coaster, which takes you on a 128-foot drop through a mountain at speeds nearing 70 mph, as well as the Lightning Rod, a wood and steel hybrid coaster. Little kids will also stay happy and entertained at Dollywood thanks to small rides like Black Bear Trail and the Busy Bees ride. The resort's water park features a lazy river and plenty of slides.",
        price: 200,
      },
      {
        ownerId: 1,
        address: "1 Legoland Dr",
        city: "Carlsbad",
        state: "California",
        country: "United States of America",
        lat: 33.072160,
        lng: -117.182400,
        name: "Legoland",
        description: "Plan your next LEGOLAND® California visit and build memories that last a lifetime at our theme park, water park, aquarium, and 2 fully themed Resort hotels.",
        price: 120,
      },
       {
        ownerId: 3,
        address: "100 Hersheypark Drive",
        city: "Hershey",
        state: "Pennsylvania",
        country: "United States of America",
        lat: 32,
        lng: 32,
        name: "Herseypark",
        description:"Hersheypark gives chocolate lovers a cause to rally around. Not only does this theme park boast an array of roller coasters, family rides and water rides, but it is home to Hershey's Chocolate World, with every possible chocolate concoction and dessert imaginable.",
        price: 80,
      },
      {
        ownerId: 4,
        address: "399 Silver Dollar City Parkway",
        city: "Branson",
        state: "Missouri",
        country: "United States of America",
        lat: 32,
        lng: 32,
        name: "Silver Dollar City",
        description: "Silver Dollar City boasts both a theme park and a water park within 10 miles of the shows and attractions in downtown Branson, Missouri. The 1880s-inspired theme park itself features almost 40 rides and attractions, including spinning coasters, drop rides, swing rides and more. The White Water water park is home to 13 acres of water rides, slides, a 500,000-gallon wave pool and a lazy river.",
        price: 150,
      },
      {
        ownerId: 3,
        address: "500 Sea World Drive",
        city: "San Diego",
        state: "California",
        country:"United States of America",
        lat: 32,
        lng: 32,
        name: "SeaWorld",
        description: "Rides and roller coasters are dotted throughout SeaWorld, including swing rides, spin rides and tantalizing drop rides. Guests can also discover large coasters like the Emperor – the tallest, fastest and longest dive coaster in California. In spring 2023 the park is set to launch a brand new coaster called Arctic Rescue, which will be the fastest and longest straddle coaster on the West Coast.",
        price: 80,
      },
      {
        ownerId: 4,
        address: "1 Cedar Point Drive",
        city: "Sandusky",
        state: "Ohio",
        country: "United States of America",
        lat: 32,
        lng: 32,
        name: "Cedar Point",
        description: "Located along the shores of Lake Erie, Cedar Point is known for its diverse selection of 70-plus rides, including 18 world-class roller coasters. Notable coasters range from Steel Vengeance – boasting 30 seconds of airtime, the feeling of weightlessness – to Valravn, which drops riders from 223 feet in the air at a 90-degree angle before spinning on a 270-degree roll. Cedar Point also features events, festivals and live shows, so be sure to check the calendar before booking.",
        price: 90,
      },
      {
        ownerId: 3,
        address: "4800 Kennywood Blvd.",
        city: "West Mifflin",
        state: "Pennsylvania",
        country: "United States of America",
        lat: 32,
        lng: 32,
        name: "Kennywood",
        description: "Pennsylvania's Kennywood offers exciting roller coasters, family attractions and rides that range from mild to intense. Relaxed options for kids, like paddle boats and a merry-go-round, allow even the most tepid travelers to get a burst of adrenaline. Meanwhile, adventure-seekers can ride the Sky Rocket, which launches riders from zero to 50 mph in three seconds, or the Phantom's Revenge, a steel roller coaster that's one of Kennywood's most popular rides.",
        price: 60,
      },
      {
        ownerId: 1,
        address: "N World Dr",
        city: "Orlando",
        state: "Florida",
        country: "United States of America",
        lat: 32,
        lng: 32,
        name: "Walt Disney World",
        description: "Arguably the most famous amusement park in the world, Walt Disney World Resort inspires awe in children and adults alike. Four distinct theme parks make up the larger Walt Disney World Resort. Magic Kingdom is the resort's most iconic area, with the striking Cinderella Castle and whimsical 'it's a small world' boat ride. EPCOT delights visitors with unique dishes, rides and festivals celebrating cultures around the globe. Disney's Hollywood Studios boasts the Star Wars: Galaxy's Edge attraction, which transports guests to a galaxy far, far away. Finally, Disney's Animal Kingdom houses rare animals and numerous rides, plus the unforgettable Tree of Life.",
        price: 400,
      },
      {
        ownerId: 3,
        address: "5700 Fun Spot Way",
        city: "Orlando",
        state: "Florida",
        country: "United States of America",
        lat: 32,
        lng: 32,
        name: "Fun Spot America",
        description: "If you're looking for a more affordable theme park experience in the Orlando area, Fun Spot America should be on your radar. This theme park offers a boatload of rides and attractions for much lower prices than at nearby parks, including smaller roller coasters, drop rides, spin rides and a Ferris wheel. Fun Spot America Orlando also boasts several premium go-kart tracks for families who want to race each other.",
        price: 40,
      },
      {
        ownerId: 4,
        address: "10165 McKinley Drive",
        city: "Tampa",
        state: "Florida",
        country: "United States of America",
        lat: 32,
        lng: 32,
        name: "Busch Gardens",
        description: "Busch Gardens Tampa Bay offers theme park action and its own water park, plus a full zoo with more than 200 species of animals. The park's rides include an exhilarating triple-launch roller coaster, a family-friendly spin coaster, a 335-foot drop tower, a whitewater rafting ride and more.",
        price: 80,
      },
      {
        ownerId: 2,
        address: "6000 Universal Blvd.",
        city: "Orlando",
        state: "Florida",
        country: "United States of America",
        lat: 32,
        lng: 32,
        name: "Universal Orlando Resort",
        description: `Three distinct parks are located within Universal Orlando Resort, meaning the complex truly does offer something for everyone. Universal Studios Florida showcases characters from movies and TV series such as "Harry Potter," "Transformers," and "Despicable Me" with family-friendly rides. Universal's Islands of Adventure also features popular characters but ups the ante with more and larger rides. Finally, Universal's Volcano Bay Water Theme Park provides slides and pools galore for soaking up the sun.`,
        price: 150,
      },
      //  {
      //   ownerId: 3,
      //   address: "6300 Kings Island Drive",
      //   city: "Mason",
      //   state: "Ohio",
      //   country: "United States of America",
      //   lat: 32,
      //   lng: 32,
      //   name: "Kings Island",
      //   description: "Kings Island is a 364-acre theme park with its own water park located about 25 miles north of Cincinnati, Ohio. Rides for little kids are front and center here, with a carousel, bumper cars, small roller coasters and more at Planet Snoopy. Thrill-seekers won't be disappointed, however, since Kings Island also offers more than a dozen adventurous coasters and rides for older visitors.",
      //   price: 50,
      // },
      // {
      //   ownerId: 4,
      //   address: "391 Knoebels Blvd.",
      //   city: "Elysburg",
      //   state: "Pennsylvania",
      //   country: "United States of America",
      //   lat: 32,
      //   lng: 32,
      //   name: "Knoebels Amusement Resort",
      //   description: "Pennsylvania's Knoebels Amusement Resort offers three kinds of rides to maximize the fun: kiddie rides, family rides and thrill rides. The family-oriented options are just what you'd expect at a top amusement park. Rides for older and more adventurous guests include the Black Diamond mine car ride through spooky coal mines; the Giant Flume ride, which whisks guests through various areas along a river while getting them wet; and the Impulse coaster, with four upside-down turns and a 90-degree free fall.",
      //   price: 60,
      // },
    ], {})
  },

  down: async (queryInterface, Sequelize) => {
    options.tableName = 'Spots';
    const Op = Sequelize.Op;
    return queryInterface.bulkDelete(options,{
      address:{ [Op.in]:['123 Disney Lane', '6561 Beach Boulevard','26101 Magic Mountain Pkwy','100 Universal City Plaza', "2700 Dollywood Parks Blvd","1 Legoland Dr",
      "100 Hersheypark Drive","399 Silver Dollar City Parkway","500 Sea World Drive","1 Cedar Point Drive", "4800 Kennywood Blvd.","N World Dr","5700 Fun Spot Way",
      "10165 McKinley Drive","6000 Universal Blvd."]}
    }, {});
  }
};
